Bootstrap: docker
From: debian:jessie-slim

#Include git,gcc, idba, trimmomatic,

%post
    # INSTALLING SOME DEPENDENCIES
    apt-get install --yes sudo

    sudo apt-get --yes update
    sudo apt-get --yes install locales

    sudo locale-gen en_US.UTF-8
    sudo update-locale

    sudo apt-get --yes install build-essential ca-certificates openjdk-7-jre \
    git gcc make autoconf automake wget git zlib1g-dev libbz2-dev \
    libncurses5-dev curl unzip python-dev liblzma-dev libcurl4-openssl-dev \
    software-properties-common apt-transport-https \
    && rm -rf /var/lib/apt/lists/*

    ## IDBA
    cd /opt
    git clone https://github.com/loneknightpy/idba \
    && cd idba \
    && sed -i 's/kMaxShortSequence = 128/kMaxShortSequence = 500/' src/sequence/short_sequence.h \
    && ./build.sh \
    && make
    cd /usr/local/bin
    ln -s /opt/idba/bin/idba_ud
    ln -s /opt/idba/bin/fq2fa
    cd /
    TRIMMOMATIC_SOURCE="Trimmomatic-0.36.zip" \
    TRIMMOMATIC_HOME="/opt/trimmomatic"
    wget http://www.usadellab.org/cms/uploads/supplementary/Trimmomatic/Trimmomatic-0.36.zip -O /opt/trimmomatic.zip && \
    unzip /opt/trimmomatic.zip -d /opt/ && \
    rm /opt/trimmomatic.zip
    cd /

    # SAMTOOLS
    #HTSLIB_VERSION=1.8 # indexes versions for samtools and bcftools
    #wget -O "samtools.tar.gz" https://github.com/samtools/samtools/archive/${HTSLIB_VERSION}.tar.gz
    #tar xf samtools.tar.gz
    #cd samtools-${HTSLIB_VERSION}
    #autoheader
    #autoconf -Wno-syntax
    #./configure --prefix /usr/local
    #make
    #sudo make install
    #cd /

    # BWA
    #BWA_VERSION=0.7.17
    #wget -O "bwa.tar.gz" https://github.com/lh3/bwa/archive/v${BWA_VERSION}.tar.gz
    #tar xf bwa.tar.gz
    #cd bwa-${BWA_VERSION}
    #make && sudo mv bwa /usr/local/bin
    #cd /
    
    # Bedtools
    #cd /usr/local/
    #aria2c -x 6 -s 6 https://github.com/arq5x/bedtools2/releases/download/v2.27.1/bedtools-2.27.1.tar.gz
    #tar -zxvf bedtools-2.27.1.tar.gz
    #cd /usr/local/bedtools2
    #make
    #ln -s /usr/local/bedtools2/bin/* /usr/local/bin/
    #cd /
    
    # freebayes
    #cd /usr/local
    #git clone --recursive git://github.com/ekg/freebayes.git
    #cd freebayes
    #make
    #cd /
   
    # vcflibs 
    #cd /usr/local
    #git clone --recursive git://github.com/ekg/vcflib.git
    #cd vcflib
    #make
    #cd /

%test
    which idba_ud
