Bootstrap: docker
From: debian:jessie-slim


%post
    apt update \
    && apt install -y --no-install-recommends \
    build-essential \
    ca-certificates \
    git \
    gcc \
    make \
    automake \
    autoconf \
    openjdk-7-jre \
    wget \
    unzip \
    sed \
    && rm -rf /var/lib/apt/lists/*
    cd /opt
    git clone https://github.com/loneknightpy/idba \
    && cd idba \
    && sed -i 's/kMaxShortSequence = 128/kMaxShortSequence = 500/' src/sequence/short_sequence.h \
    && ./build.sh \
    && make
    cd /usr/local/bin
    ln -s /opt/idba/bin/idba_ud
    ln -s /opt/idba/bin/fq2fa
    cd /
    TRIMMOMATIC_SOURCE="Trimmomatic-0.36.zip" \
    TRIMMOMATIC_HOME="/opt/trimmomatic"
    wget http://www.usadellab.org/cms/uploads/supplementary/Trimmomatic/Trimmomatic-0.36.zip -O /opt/trimmomatic.zip && \
    unzip /opt/trimmomatic.zip -d /opt/ && \
    rm /opt/trimmomatic.zip
    cd /
    
    # Code for python download
    apt-get -y update
    apt-get -y install eatmydata

    eatmydata apt-get install -y locales

    # Based on rocker.
    echo "en_US.UTF-8 UTF-8" >> /etc/locale.gen \
      && locale-gen en_US.utf8 \
      && /usr/sbin/update-locale LANG=en_US.UTF-8

    eatmydata apt-get install -y --no-install-recommends \
      libcurl4-openssl-dev libssl-dev zlib1g-dev fonts-texgyre \
      gcc g++ gfortran libblas-dev liblapack-dev \
      make git git-annex-standalone pandoc \
      python3-docopt python3-pytest \
      r-base-core r-recommended r-cran-littler \
      dos2unix snakemake

    apt-get clean
    rm -rf /var/lib/apt/lists/


    
%test
    which idba_ud

